# Generated by Django 5.0.6 on 2024-06-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='max_salary',
            field=models.BigIntegerField(default=24000),
            preserve_default=False,
        ),
    ]
